GitHub Copilot: A Panel in pandas is a three-dimensional data structure with labeled axes. It can be thought of as a container of DataFrame objects. The term Panel comes from econometrics and is partially responsible for the name pandas: pan(el)-da(ta)-s.

However, as of pandas version 0.20.0, Panel is deprecated and its use is not recommended. Instead, you should use multi-indexing (MultiIndex) or other data structures like xarray package to handle 3-dimensional data.

Here's an example of how you could create a Panel (prior to deprecation):

```python
import pandas as pd
import numpy as np

data = np.random.rand(2,4,5)
p = pd.Panel(data)
print(p)
```

In this example, `data` is a 3-dimensional numpy array, and `pd.Panel(data)` creates a Panel from this data.

But again, it's important to note that Panel is deprecated and its use is not recommended in newer versions of pandas.

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../Datasets/LVC Datasets/Lesson_6/vgsales.csv')

In [6]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [11]:
df.set_index(['Rank', 'Name'])

,,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,Name,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [15]:
pd.MultiIndex.from_frame(df)

MultiIndex([(    1, ...),
            (    2, ...),
            (    3, ...),
            (    4, ...),
            (    5, ...),
            (    6, ...),
            (    7, ...),
            (    8, ...),
            (    9, ...),
            (   10, ...),
            ...
            (16591, ...),
            (16592, ...),
            (16593, ...),
            (16594, ...),
            (16595, ...),
            (16596, ...),
            (16597, ...),
            (16598, ...),
            (16599, ...),
            (16600, ...)],
           names=['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'], length=16598)

In [29]:
# pd.MultiIndex.from_frame(df['Name', 'Year'], names=['Name', 'Year'])
df.loc['Name']

KeyError: 'Name'

In [30]:
import pandas as pd

# List of tuples
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

# Create MultiIndex
index = pd.MultiIndex.from_tuples(index, names=['State', 'Year'])

# Create DataFrame
df = pd.DataFrame({'Population': [33871648, 37253956,
                                  18976457, 19378102,
                                  20851820, 25145561]}, index=index)

print(df)

                 Population
State      Year
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [31]:
print(df.loc['California', 2000])

Population    33871648
Name: (California, 2000), dtype: int64